# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20171008_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=b'media'),
        ),
    ]
